Another Bitwarden Shit

diff --git a/rarbs b/rarbs
--- a/rarbs
+++ b/rarbs
@@ -64,10 +64,12 @@ main() { \
 		sed -i "s/-j2/-j$(nproc)/;s/^#MAKEFLAGS/MAKEFLAGS/" /etc/makepkg.conf
 
 		# manualinstall $aurhelper || error "Failed to install AUR helper."
-		manualinstall paru-bin || error "Failed to install $aurhelper (AUR helper)."
+		manualinstall paru-bin || manualinstall $aurhelper || error "Failed to install $aurhelper (AUR helper)."
 
 		# Get bitwarden user and verify email and password
-		isuserbw || error "User Exited"
+		if [ ! -z $is_secret ]; then 
+			isuserbw || error "User Exited"
+		fi
 
 		# The command that does all the installing. Reads the progs.csv file and
 		# installs each needed program the way required. Be sure to run this only after
@@ -137,7 +139,9 @@ main() { \
 		installationloop
 
 		# Get bitwarden user and verify email and password
-		isuserbw || error "User Exited"
+		if [ ! -z $is_secret ]; then 
+			isuserbw || error "User Exited"
+		fi
 
 		chezmoiinstall "$dotfilesrepo"
 		# put some default config here for macOS  (Boostraping setting)
