fix typo

diff --git a/rarbs b/rarbs
--- a/rarbs
+++ b/rarbs
@@ -9,6 +9,17 @@ while getopts ":a:r:b:p:s:h" o; do case "${o}" in
 	*) printf "Invalid option: -%s\\n" "$OPTARG" && exit 1 ;;
 esac done
 
+getOS() { \
+	case "$OSTYPE" in
+	  darwin*)  OS="MacOS" && installMac ;;
+	  linux*)   OS="ArchLinux" && installLin ;;
+	  msys*)    OS="Windows" && installWin ;;
+	  bsd*)     OS="BSD" ;;
+	  solaris*) OS="SOLARIS" ;;
+	  *)        error "unknown OS: $OSTYPE" ;;
+	esac
+}
+
 [ -z "$dotfilesrepo" ] && dotfilesrepo="https://github.com/romariorobby/dotfiles.git"
 [ -z "$sshdotfilesrepo" ] && sshdotfilesrepo="git@github.com:romariorobby/dotfiles.git"
 [ -z "$progsfile" ] && progsfile="https://raw.githubusercontent.com/romariorobby/rarbs/master/progs.csv"
@@ -50,7 +61,7 @@ installawesome(){ \
 	dialog --title "RARBS WM/DE" --infobox "Installing \`Awesome\`" 5 70
 	installpkg awesome
 	if [ ! -d "$awmdir" ];then
-		sudo -u "$name" mkdir $awmdir
+		sudo -u "$name" mkdir -p $awmdir
 		sudo -u "$name" cp /etc/xdg/awesome/rc.lua $awmdir
 		# change default term,editor, and close binding
 		sudo -u "$name" sed -i 's/xterm/kitty/g;s/nano/nvim/g;s/"c"/"q"/g' $awmdir/rc.lua
@@ -535,21 +546,10 @@ finalize(){ \
 		dialog --title "All done, LINUX!" --msgbox "Congrats! Provided there were no hidden errors, the script completed successfully and all the programs and configuration files should be in place.\\n\\nTo run the new graphical environment, log out and log back in as your new user, then run the command \"startx\" to start the graphical environment (it will start automatically in tty1).\\n\\n.t Romario" 12 80
 	fi
 }
-installpkg dialog || error "Are you sure you're running this as the root user, are on an $OS and have an internet connection?"
+laptopconf(){ \
 
-# Welcome user and pick dotfiles.
-welcomemsg || error "User Exited"
-
-# Rarbs mode
-modepick || error "modepick error"
-
+}
 mpickI() { \
-	# Pick type Minimal or Full?
-	rarbtype || error "rarbtype error"
-
-	# Pick Windows Manager
-	installationloop || error "Installationloop error"
-
 	# Get and verify username and password.
 	getuserandpass || error "User exited."
 
@@ -562,7 +562,7 @@ mpickI() { \
 	# Refresh Arch keyrings.
 	refreshkeys || error "Error automatically refreshing Arch keyring. Consider doing so manually."
 
-	for x in curl base-devel git ntp zsh; do
+	for x in curl base-devel dmidecode git ntp zsh; do
 		dialog --title "RARBS Installation" --infobox "Installing \`$x\` which is required to install and configure other programs." 5 70
 		installpkg "$x"
 	done
@@ -578,8 +578,9 @@ mpickI() { \
 	# in a fakeroot environment, this is required for all builds with AUR.
 	newperms "%wheel ALL=(ALL) NOPASSWD: ALL"
 
-	# Make pacman and yay colorful and adds eye candy on the progress bar because why not.
+	# Make pacman and yay colorful, Enable Parallel Download and adds eye candy on the progress bar because why not.
 	grep -q "^Color" /etc/pacman.conf || sed -i "s/^#Color$/Color/" /etc/pacman.conf
+	grep -q "^ParallelDownloads" /etc/pacman.conf || sed -i "s/#Parallel/Paralell/" /etc/pacman.conf
 	grep -q "ILoveCandy" /etc/pacman.conf || sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf
 
 	# Use all cores for compilation.
@@ -597,12 +598,11 @@ mpickI() { \
 	# and all build dependencies are installed.
 	installationloop
 
-	#Install Windows Manager
+	# Pick & Install Windows Manager
 	wmdeinstall
-	# 
+
 	dialog --title "RARBS Installation" --infobox "Finally, installing \`libxft-bgra\` to enable color emoji in suckless software without crashes." 5 70
 	yes | sudo -u "$name" $aurhelper -S libxft-bgra-git >/dev/null 2>&1
-
 
 	# Most important command! Get rid of the beep!
 	systembeepoff
@@ -614,8 +614,15 @@ mpickI() { \
 	chezmoiinstall "$dotfilesrepo"
 
 	# Tap to click
-	# TODO: Check  with `dmidecode --string chassis-type` to know if you're runing laptop or desktop
-	dmidecode --string chassis-type | grep "Notebook" && [ ! -f /etc/X11/xorg.conf.d/40-libinput.conf ] && printf 'Section "InputClass"
+	if [ -x "$(command -v "dmidecode")" ]; then
+		#https://superuser.com/questions/877677/programatically-determine-if-an-script-is-being-executed-on-laptop-or-desktop
+		is_chassis=$(dmidecode --string chassis-type)
+	else
+		# Systemd Spesific
+		is_chassis=$(hostnamectl chassis)
+	fi
+	[ "is_chassis" == "Notebook" ] || [ "$is_chassis" = "laptop" ] && \
+		"[ ! -f /etc/X11/xorg.conf.d/40-libinput.conf ] && printf 'Section "InputClass"
 			Identifier "libinput touchpad catchall"
 			MatchIsTouchpad "on"
 			MatchDevicePath "/dev/input/event*"
@@ -651,8 +658,6 @@ mpickD() { \
 }
 mpickR(){
 	name=$(echo $USER)
-	# Pick type Minimal or Full?
-	rarbtype || error "rarbtype error"
 
 	# Pick Windows Manager
 	wmdepick || error "wmdepick error"
@@ -685,14 +690,10 @@ installLin(){ \
 		"R") mpickR ;;
 		"D") mpickD ;;
 	esac
-	finalize
-	clear
-}
-installMac(){\
-	insbrew || error "User Exited"
 
-	# Pick type Minimal or Full?
-	rarbtype || error "rarbtype error"
+}
+installMac(){ \
+	insbrew || error "User Exited"
 
 	for x in curl git ntp zsh; do
 		dialog --title "RARBS Installation" --infobox "Installing \`$x\` which is required to install and configure other programs." 5 70
@@ -709,6 +710,27 @@ installMac(){\
 	# opt/macosdefault.sh
 	#
 	# cleanup
+
+}
+main(){ \
+	installpkg dialog || error "Are you sure you're running this as the root user, are on an $OS and have an internet connection?"
+
+	# Welcome user and pick dotfiles.
+	welcomemsg || error "User Exited"
+
+	# Rarbs mode
+	modepick || error "modepick error"
+
+	# Type Pick
+	typepick || error "Error Picking type"
+	case "$OSTYPE" in
+		darwin*)  installMac ;;
+		linux*)   installLin ;;
+		msys*)    installWin ;;
+		bsd*)     error "$OSTYPE Not yet supported";;
+		solaris*) error "$OSTYPE Not yet supported";;
+		*)        error "unknown OS: $OSTYPE" ;;
+	esac
 	finalize
 	clear
 
@@ -717,12 +739,4 @@ installWin(){\
 	echo "windows"
 
 }
-
-case "$OSTYPE" in
-  darwin*)  OS="MacOS" && installMac ;;
-  linux*)   OS="ArchLinux" && installLin ;;
-  msys*)    OS="Windows" && installWin ;;
-  bsd*)     OS="BSD" ;;
-  solaris*) OS="SOLARIS" ;;
-  *)        error "unknown OS: $OSTYPE" ;;
-esac
+main "$@"
